site_name: Leaf Docs
theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
  icon:
    annotation: material/plus-circle

extra:
  # i18n system
  alternate:
    - name: English
      link: /en/ 
      lang: en
    - name: 简体中文
      link: /zh/
      lang: zh

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.superfences